name: Challenges
main: us.corenetwork.challenges.Challenges
version: 1.0.1
author: matejdro
depend: [WorldEdit, WorldGuard, GroupManager]
commands:
    cha:
        description: Weekly challenges.
    chm:
        description: Weekly challenges.
    ch:
        description: Weekly challenges.
    done:
        description: Finished typing challenge
    points:
        description: Check your current amount of points.