name: MCNSAChallenges
main: com.matejdro.bukkit.mcnsa.challenges.MCNSAChallenges
version: 1.0.1
author: matejdro
depend: [WorldEdit, WorldGuard, GroupManager]
commands:
    cha:
        description: Weekly challenges.
    chm:
        description: Weekly challenges.
    ch:
        description: Weekly challenges.
    points:
        description: Check your current amount of points.
permissions:
    mcnsachallenges.command.ch:
        default: true
    mcnsachallenges.command.cha:
        default: op
    mcnsachallenges.command.chm:
        default: op
    mcnsachallenges.notify:
        default: op
