name: Challenges
main: us.corenetwork.challenges.Challenges
version: 1.0.2
author: matejdro
depend: [WorldEdit, WorldGuard, Vault]
commands:
    cha:
        description: Weekly challenges.
    chm:
        description: Weekly challenges.
    ch:
        description: Weekly challenges.
    ok:
        description: Finished typing challenge
    points:
        description: Check your current amount of points.